CREATE TABLE BOOKED(Passenger_ssn CHAR(9) NOT NULL PRIMARY KEY, Train_Number INT  NOT NULL, Ticket_type VARCHAR(7) NOT NULL, Status VARCHAR(6) NOT NULL);
CREATE TABLE PASSENGER(first_name VARCHAR(35) NOT NULL, last_name VARCHAR(35) NOT NULL, address VARCHAR(50) NOT NULL, city VARCHAR(20) NOT NULL, county VARCHAR(20) NOT NULL, phone VARCHAR(12) NOT NULL, SSN CHAR(9) NOT NULL, bdate DATE NOT NULL, PRIMARY KEY (SSN), FOREIGN KEY(SSN) REFERENCES BOOKED(Passenger_ssn));
CREATE TABLE TRAIN_STATUS(TrainDate DATE NOT NULL, TrainName VARCHAR(20) NOT NULL, PremiumSeatsAvailable INT, GenSeatsAvailable INT, PremiumSeatsOccupied INT, GenSeatsOccupied INT);
CREATE TABLE Train(Train Number INT NOT NULL, Train Name VARCHAR(20) NOT NULL, Premium Fair INT NOT NULL, General Fair INT NOT NULL, Source Station VARCHAR(20) NOT NULL, Destination_Station VARCHAR(20) NOT NULL, Available_on VARCHAR(50));

